name: Build and Deploy R Markdown Site to GitHub Pages

# Trigger on pushes to your default branch (change "main" if necessary)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # 3. Install dependencies
      #
      # You might want to customize this step if you have a package
      # or use a different mechanism to install required packages.
      - name: Install R Packages
        run: |
          Rscript -e "install.packages(c('rmarkdown', 'knitr'), repos = 'https://cloud.r-project.org')"
          # If you have additional packages (or a package dependency file), install them here.

      # 4. Build the site
      #
      # This assumes you’re using R’s built-in website functionality (i.e. a _site.yml file)
      # If you use a custom script or package like blogdown, modify accordingly.
      - name: Build Site
        run: |
          Rscript -e "rmarkdown::render_site()"
        # By default, rmarkdown::render_site() writes the output to a folder named `_site`
        # (unless you have configured a different output_dir in _site.yml)

      # 5. Deploy to GitHub Pages
      #
      # This step uses the popular peaceiris/actions-gh-pages action.
      # Adjust the publish_dir if your built site is output to a different folder.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

